---

name: "Code Quality: Brew"

on:
  push:
    branches: master
  pull_request: []

jobs:
  brew-testbot:
    runs-on: macos-latest
    name: brew-testbot

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run brew test-bot
        run: |
          set -e
          brew update
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/operatehappy/homebrew-hashicorp"
          mkdir -p "${HOMEBREW_TAP_DIR}"
          rm -rf "${HOMEBREW_TAP_DIR}"
          ln -s "${PWD}" "${HOMEBREW_TAP_DIR}"
          brew test-bot --fail-fast
