---

name: "Code Quality: Brew"

on:
  push:
    branches: master
  pull_request: []

jobs:
  brew-testbot:
    runs-on: macos-latest
    name: brew-testbot

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up brew test-bot environment
        run: |
          brew update
          mkdir -p "${HOMEBREW_TAP_DIR}"

          rm -rf "${HOMEBREW_TAP_DIR}"
          ln -s "${PWD}" "${HOMEBREW_TAP_DIR}"
        env:
          HOMEBREW_TAP_DIR: "/usr/local/Homebrew/Library/Taps/operatehappy/homebrew-hashicorp"

      - name: Run brew test-bot
        run: |
          brew test-bot --fail-fast
        env:
          HOMEBREW_TAP_DIR: "/usr/local/Homebrew/Library/Taps/operatehappy/homebrew-hashicorp"

      - name: Run brew cask audit
        run: |
          brew cask audit
        env:
          HOMEBREW_TAP_DIR: "/usr/local/Homebrew/Library/Taps/operatehappy/homebrew-hashicorp"
